### PR TITLE
Add new test for xregister, imcombine, and combine. A first start.

### PR DESCRIPTION
**Pull request by steelewool**
This test (image.immatch.regAndCombine.md) is a first cut at testing the xregister and combine functions on the raspberry pi. This test also works on my linux64 machine.

### CODE REVIEW

**Comment by olebole** [comment]
Sorry, this isn't ready for merge yet:

* It is not really markdown formatted
* The CI test fails (because the test is running in a separate, empty directory)
* I don't like (yet) the idea of polluting the test dir with many test files. Especially when they are not really specific. Please create test files like 1x1-pixel-files on the fly for the test -- IRAF should have the tools for that.
* Don't just mark a test that fails due to the date with `xfail`; you may decrease verbosity (so that the date is not printed anymore), or filter it out with the `match` task.

**Comment by steelewool** [comment]
I have to agree with you. I think the test is important, but needs more
refinement before going into a repository. I'll look to update it.

**Comment by olebole** [comment]
Since this seems to me not relevant anymore, I am closing it. Please tell me if this was on error.

**Comment by steelewool** [comment]
Your call. No problem with this on my end.

**Pull request closed without merging**
