### PR TITLE
Add additional README for the RaspberryPi

### PR DESCRIPTION
**Pull request by steelewool**
Just added the README.raspberryPi as a spot to recored differences between running on the Pi another platforms/

### CODE REVIEW

**Comment by olebole** [comment]
Hmm, I don't see why this is Raspberry specific. Also, the comment "latest vesion in the directory /home/pi/Downloads/SAOImageDS9/bin" is misleading for a common README.

What is the problem with older DS9 versions, BTW?

**Comment by steelewool** [comment]
The problem with ds9 is a version issue. The synaptic package manage is
installing an older version of ds9 which is incompatible with iraf. The
newer version of ds9 works well after the envirnoment variables are set.

Rejected my README that is specific to the Raspberry pi seems like a
reasonable decision to me. But, I'd like to see a collection of which
version of external software are required to run iraf. If you agree with
this - where would you like to see it placed?

Also, my comment should have been more general.

Rob

**Comment by olebole** [comment]
What is the problem with DS9? Can you specify that?

**Comment by steelewool** [comment]
Doesn't work doesn't cut huh. :)

In all seriousness, iraf crashed when I attempted to use the older version
of ds9. I did not record the error but when I looked things up on the iraf
forum others had the same issue. The fix, as put forth by Fritz, was just
to get the latest version of ds9 - which I did.

Rob

**Comment by olebole** [comment]
If IRAF crashes, it has a bug, which we should fix and not just work around. Therefore, I would really ask you to create a reproducible bug report instead of just putting it into the README. Fitz may be lazy about buggy software, but I am not.
Checking the [DS9 commit history](https://github.com/SAOImageDS9/SAOImageDS9/blob/10be130ee5bfadf4dcab5fca87e7de89218739d3/ds9/doc/release/r7.6.html#L133-L147), I could at least not find that there was a fix or so.

**Comment by steelewool** [comment]
I'll go ahead and reproduce the problem, document it, and the move forward
with fixing the bug. I know it fails on the RaspberryPi on the porting
branch but I'll look for other failures.

Should the display function work in the test harness. My initial use of it
failed and I thought maybe it was user error. But, if this is a bug it
would be good to have a test that shows that it has been fixed.

Rob

**Comment by steelewool** [comment]
It was operator error. I've got a .md file that doesn't crash the newer
version of ds9 - but crashes the old version.

Rob

**Comment by olebole** [comment]
Since this seems to me not relevant anymore, I am closing it. Please tell me if this was on error.

**Pull request closed without merging**
